Import Library

In [2]:
import cv2
import numpy as np

Membaca Citra

In [4]:
citra = cv2.imread('Capybara.jpg')

In [5]:
cv2.imshow("citra asli", citra)
cv2.waitKey(10)
cv2.destroyAllWindows()

Dimensi Citra

In [7]:
print(citra.shape)
print(citra.dtype)

(4000, 4000, 3)
uint8


Splitting Citra RGB/BGR

In [8]:
b = citra[:,:,0] #biru 0
g = citra[:,:,1] #hijau 1
r = citra[:,:,2] #merah 2 

RGB to Grayscale

In [24]:
panjang = len(citra) #menghitung baris
lebar = len(citra[0]) #menghitung kolom

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra gray", citra_gray)
cv2.waitKey(10)
cv2.destroyAllWindows()

In [26]:
print(citra)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [28]:
print(citra_gray)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


In [34]:
panjang = len(citra) 
lebar = len(citra[0]) 

ambang = 120
#skala penggunaan hitam atau putih untuk gambar

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih
        else :
            citra_biner[i,j] = 0 #hitam 
        
cv2.imshow("citra binary", citra_biner)
cv2.waitKey(10)
cv2.destroyAllWindows()

In [36]:
print(citra_gray)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


In [38]:
print(citra_biner)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [40]:
print(citra_biner[50,50])

1.0
